apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nano-tech-sharing
  annotations:
    github.com/project-slug: tommyhutomo/nano-tech-sharing
spec:
  type: other
  lifecycle: unknown
  owner: guests
